[project]
name = "FewShotX"
version = "0.1.2"
description = "Few-shot learning for text classification"
authors = [
  { name = "Renato Vassallo", email = "renato.vassallo@bse.eu" }
]
readme = "README.md"
requires-python = ">=3.11,<3.12"

# Mandatory dependencies
dependencies = [
    "accelerate>=1.6.0",
    "huggingface-hub[hf-xet]>=0.30.2",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.6",
    "matplotlib>=3.10.1",
    "numpy>=1.24.4",      #2.2.5 
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "pyarrow>=20.0.0",
    "seaborn>=0.13.2",
    "sentence-transformers>=4.1.0",
    "spacy>=3.8.5"
]

[project.optional-dependencies]
# Optional dependencies for development and testing
dev = [
    "pyarrow>=20.0.0",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.6",
    "dropbox>=12.0.2",
    "matplotlib>=3.10.1",
    "python-dotenv>=1.1.0",
    "seaborn>=0.13.2",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.astral-uv.package-data]
FewShotX = ["datasets/*.parquet", "datasets/*.csv"]

[tool.astral-uv]
source-dir = "src"